ConnectionURL=http://sundarnatarajan_iqyk45:wtYGx3ewdxiUVMBvSFX8@hub-cloud.browserstack.com/wd/hub
App_Environment=QA
TestType=smoke

App_Version=Android - Version 3.95.019 (92) & iOS - 3.95.026 (72)

QA_URL=NA
MobileTestExecutionPlatform=BrowserStack
#App_Path_Android=bs://c5f215a5cc46e0205940ec7493a525ef44b3d7bb (2.11.0)
App_Path_Android=bs://0882dc2c9caaa9fac3f13d49486c913c13e48550 
#App_Path_iOS=bs://c5f215a5cc46e0205940ec7493a525ef44b3d7bb ( 2.11.0)
App_Path_iOS=bs://2252459fbfdeb65d27a17e8b5a0761a3180cc5fc
ExecutionPlatform=Mobile
OS_ExecutionPlatform=IOS
#OS_ExecutionPlatform=Android
Orientation=PORTRAIT
AndroidDeviceName=Google Pixel 9
iOSDeviceName=iPhone 15 Pro
UserAccount=Batch1

App_URL=NA
Browser=chrome

PIPELINE_EXECUTION=false
CaptureScreenShotsOnlyForFailure=False
BASE_URL=na