#ConnectionURL=http://sundarnatarajan_iqyk45:wtYGx3ewdxiUVMBvSFX8@hub-cloud.browserstack.com/wd/hub
#ConnectionURL=http://sundarn1:P07oQRc8akOpHI5hvIyW@hub-cloud.browserstack.com/wd/hub
#DGov
ConnectionURL=http://dgovtest_rqtbfv:W1b4uz2t7PTGepE9ZPpn@hub-cloud.browserstack.com/wd/hub
App_Environment=QA
TestType=smoke

App_Version=Android - Version 3.95.019 (92) & iOS - 3.95.026 (72)

QA_URL=NA
MobileTestExecutionPlatform=BrowserStack
#DPC BrowserStack details (2.11.3)
App_Path_iOS=bs://1577ec691f1cfb4f209ddf2ef3dcc9617f8d1040
App_Path_Android=bs://a25404962769414af15b59e50222494bb4411255


#Sundar Browserstack details (2.11.2)
#App_Path_Android=bs://5a7697a17e0f28bab9e574a0aefb120ff36c9bf1
#App_Path_iOS=bs://5482c140cdcc7cd10bd95f96139409136309d0c2

#Sundar Browserstack details (2.11.3)
#App_Path_Android=bs://919273f5c476d43a2635cb74b5ae865ae94baf8e
#App_Path_iOS=bs://94012cddca0ba007a2b32c7e5eb1575f998df6ee

ExecutionPlatform=Mobile
OS_ExecutionPlatform=IOS
#OS_ExecutionPlatform=Android
Orientation=PORTRAIT
AndroidDeviceName=Samsung Galaxy S23
iOSDeviceName=iPhone 15 Pro
UserAccount=Batch1

App_URL=NA
Browser=chrome

PIPELINE_EXECUTION=false
CaptureScreenShotsOnlyForFailure=False
BASE_URL=na